"""Pine Script v6 generator for one trade plan (entry / stop / target / risk).

The script is a TradingView `strategy()`:
  - places ONE limit entry at the planned price, only from the signal bar onwards,
    cancelled if it has not filled by the entry deadline;
  - attaches the stop-loss and take-profit from the plan;
  - sizes the position so a stop-out loses `risk_amount` (qty = risk / |entry - stop|);
  - draws entry/SL/TP lines and a risk:reward label; fires webhook-ready alerts on fill/exit.

Deriv is not a TradingView broker, so TradingView cannot route this to Deriv. Use it in
the Strategy Tester / paper trading to see the exact levels the platform trades; Deriv
orders are placed by the platform's engine (demo-locked).
"""
from __future__ import annotations

from datetime import datetime, timezone


def _num(x: float) -> str:
    return f"{x:.6f}".rstrip("0").rstrip(".") if isinstance(x, float) else str(x)


def pine_for_plan(*, symbol: str, direction: str, entry: float, stop: float, target: float, risk_amount: float,
                  signal_time: int, expires_at: int | None = None, signal_id: str = "manual",
                  strategy_name: str = "ICT 2022 model", confidence: float | None = None,
                  currency: str = "USD") -> str:
    if direction not in {"long", "short"}:
        raise ValueError("direction must be long or short")
    if (direction == "long" and not stop < entry < target) or (direction == "short" and not target < entry < stop):
        raise ValueError("levels are inconsistent with the direction (long: stop < entry < target)")
    risk_px = abs(entry - stop)
    rr = abs(target - entry) / risk_px
    qty = risk_amount / risk_px
    expires_at = expires_at or signal_time + 6 * 3600
    tv_symbol = symbol.removeprefix("frx").removeprefix("OTC_")
    when = datetime.fromtimestamp(signal_time, timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    side = "strategy.long" if direction == "long" else "strategy.short"
    conf = f"{confidence:.2f}" if confidence is not None else "n/a"
    return f"""//@version=6
// Generated by fx-scalper for signal {signal_id} ({when}). Symbol on Deriv: {symbol}; chart it as {tv_symbol}.
// {direction.upper()} entry {_num(entry)} | stop {_num(stop)} | target {_num(target)} | R:R {rr:.2f}
// Risk {risk_amount} {currency} -> size {qty:.6g} units (risk / |entry - stop|)
// Ensemble confidence: {conf}. Educational tool, not financial advice. Deriv is not a TradingView broker:
// use this in the Strategy Tester / paper trading; the platform engine places the Deriv (demo) order.
strategy("{strategy_name} · {tv_symbol} {direction} · {signal_id}", overlay = true, pyramiding = 0,
         initial_capital = 1000, currency = currency.{currency}, calc_on_every_tick = true)

entryPrice  = input.float({_num(entry)}, "Entry (limit)")
stopPrice   = input.float({_num(stop)}, "Stop loss")
targetPrice = input.float({_num(target)}, "Take profit")
riskAmount  = input.float({risk_amount}, "Risk per trade ({currency})", minval = 0.01)
signalTime  = input.time({signal_time * 1000}, "Signal time")
expiryTime  = input.time({expires_at * 1000}, "Cancel entry if unfilled by")

qty = riskAmount / math.abs(entryPrice - stopPrice)
active = time >= signalTime and time <= expiryTime

if active and strategy.position_size == 0 and strategy.opentrades == 0
    strategy.entry("ICT", {side}, qty = qty, limit = entryPrice,
                   alert_message = '{{"event":"filled","signal":"{signal_id}","price":' +
                   str.tostring(entryPrice) + '}}')
if time > expiryTime and strategy.position_size == 0
    strategy.cancel("ICT")
strategy.exit("SL/TP", from_entry = "ICT", stop = stopPrice, limit = targetPrice,
              alert_message = '{{"event":"exit","signal":"{signal_id}"}}')

var line lEntry  = line.new(bar_index, entryPrice, bar_index + 1, entryPrice, extend = extend.right,
                            color = color.blue)
var line lStop   = line.new(bar_index, stopPrice, bar_index + 1, stopPrice, extend = extend.right, color = color.red)
var line lTarget = line.new(bar_index, targetPrice, bar_index + 1, targetPrice, extend = extend.right,
                            color = color.green)
if barstate.islast
    label.new(bar_index, targetPrice, "TP " + str.tostring(targetPrice) + "  (R:R {rr:.2f})", color = color.green,
              textcolor = color.white, style = label.style_label_left, size = size.small)
    label.new(bar_index, stopPrice, "SL " + str.tostring(stopPrice) + "  (risk " + str.tostring(riskAmount) + ")",
              color = color.red, textcolor = color.white, style = label.style_label_left, size = size.small)
bgcolor(active ? color.new(color.blue, 94) : na, title = "Entry window")
"""
